// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVLCUzHyLe0OJz4E9FmS-mrmim-G-g34Q',
    appId: '1:204103598391:web:9f6df0184165e09d0d9ab2',
    messagingSenderId: '204103598391',
    projectId: 'mindflow-e7840',
    authDomain: 'mindflow-e7840.firebaseapp.com',
    storageBucket: 'mindflow-e7840.firebasestorage.app',
    measurementId: 'G-40NCX8SNQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQGCwZmKKCrZUyWm3I4YzvLrTeF6EYJXc',
    appId: '1:204103598391:android:0e2dd534e8d3eb350d9ab2',
    messagingSenderId: '204103598391',
    projectId: 'mindflow-e7840',
    storageBucket: 'mindflow-e7840.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHN4VM42bnwM9iv6rtjLtZT2yjcoHJJ8E',
    appId: '1:204103598391:ios:1d150f88b7917d790d9ab2',
    messagingSenderId: '204103598391',
    projectId: 'mindflow-e7840',
    storageBucket: 'mindflow-e7840.firebasestorage.app',
    androidClientId: '204103598391-dakntmkcb2cpqcus08pvh2aicm42must.apps.googleusercontent.com',
    iosClientId: '204103598391-2ld9e8gb156svr91vdtbvvr4559jodph.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindflowMoodTrackerAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHN4VM42bnwM9iv6rtjLtZT2yjcoHJJ8E',
    appId: '1:204103598391:ios:1d150f88b7917d790d9ab2',
    messagingSenderId: '204103598391',
    projectId: 'mindflow-e7840',
    storageBucket: 'mindflow-e7840.firebasestorage.app',
    androidClientId: '204103598391-dakntmkcb2cpqcus08pvh2aicm42must.apps.googleusercontent.com',
    iosClientId: '204103598391-2ld9e8gb156svr91vdtbvvr4559jodph.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindflowMoodTrackerAppWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVLCUzHyLe0OJz4E9FmS-mrmim-G-g34Q',
    appId: '1:204103598391:web:45b6d302db0303d70d9ab2',
    messagingSenderId: '204103598391',
    projectId: 'mindflow-e7840',
    authDomain: 'mindflow-e7840.firebaseapp.com',
    storageBucket: 'mindflow-e7840.firebasestorage.app',
    measurementId: 'G-HVND6ZFYZ2',
  );
}
